wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709056167.605803
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      3:
      - 7
      - 23
      4: 3.9.18
      5: 0.16.3
      6: 4.28.1
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: eval/data/age_bias_contain_score_test\.json_loss
      5: 1
      6:
      - 1
    - 1: eval/data/age_bias_contain_score_test\.json_Preference total Acc
      5: 1
      6:
      - 1
    - 1: eval/data/age_bias_contain_score_test\.json_First-two Acc
      5: 1
      6:
      - 1
    - 1: eval/data/age_bias_contain_score_test\.json_runtime
      5: 1
      6:
      - 1
    - 1: eval/data/age_bias_contain_score_test\.json_samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/data/age_bias_contain_score_test\.json_steps_per_second
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    - 1: train/train_runtime
      5: 1
      6:
      - 1
    - 1: train/train_samples_per_second
      5: 1
      6:
      - 1
    - 1: train/train_steps_per_second
      5: 1
      6:
      - 1
    - 1: train/total_flos
      5: 1
      6:
      - 1
    - 1: train/train_loss
      5: 1
      6:
      - 1
vocab_size:
  desc: null
  value: 32000
max_position_embeddings:
  desc: null
  value: 4096
hidden_size:
  desc: null
  value: 4096
intermediate_size:
  desc: null
  value: 11008
num_hidden_layers:
  desc: null
  value: 32
num_attention_heads:
  desc: null
  value: 32
hidden_act:
  desc: null
  value: silu
initializer_range:
  desc: null
  value: 0.02
rms_norm_eps:
  desc: null
  value: 1.0e-05
use_cache:
  desc: null
  value: true
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: float16
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 512
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
chunk_size_feed_forward:
  desc: null
  value: 0
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - LlamaForCausalLM
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: 1
pad_token_id:
  desc: null
  value: 3
eos_token_id:
  desc: null
  value: 2
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: /home/student2020/srcao/meta-llama/Llama-2-7b-hf
transformers_version:
  desc: null
  value: 4.28.1
model_type:
  desc: null
  value: llama
num_key_value_heads:
  desc: null
  value: 32
pretraining_tp:
  desc: null
  value: 1
rope_scaling:
  desc: null
  value: null
output_dir:
  desc: null
  value: /home/student2020/srcao/Domina Specific Preference/age_unbiased_checkpoint/
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: true
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: steps
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 1
per_device_eval_batch_size:
  desc: null
  value: 1
per_gpu_train_batch_size:
  desc: null
  value: None
per_gpu_eval_batch_size:
  desc: null
  value: None
gradient_accumulation_steps:
  desc: null
  value: 8
eval_accumulation_steps:
  desc: null
  value: None
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 1.0e-06
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 100
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /home/student2020/srcao/Domina Specific Preference/age_unbiased_checkpoint/runs/Feb27_17-45-49_ubuntu
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 1
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: steps
save_steps:
  desc: null
  value: 300
save_total_limit:
  desc: null
  value: None
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: None
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: true
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: cuda_amp
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
xpu_backend:
  desc: null
  value: None
tpu_num_cores:
  desc: null
  value: None
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: '[]'
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 10
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: /home/student2020/srcao/Domina Specific Preference/age_unbiased_checkpoint/
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
label_names:
  desc: null
  value: None
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: None
greater_is_better:
  desc: null
  value: None
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: '[]'
fsdp:
  desc: null
  value: '[]'
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: None
deepspeed:
  desc: null
  value: configs/default_offload_opt_param.json
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: None
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value: '[''tensorboard'', ''wandb'']'
ddp_find_unused_parameters:
  desc: null
  value: None
ddp_bucket_cap_mb:
  desc: null
  value: None
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: None
hub_model_id:
  desc: null
  value: None
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: None
push_to_hub_organization:
  desc: null
  value: None
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: None
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: None
torch_compile_mode:
  desc: null
  value: None
reward_domain:
  desc: null
  value: general
padding_side:
  desc: null
  value: left
truncation_side:
  desc: null
  value: right
pooling_type:
  desc: null
  value: last
model_name_or_path:
  desc: null
  value: /home/student2020/srcao/meta-llama/Llama-2-7b-hf
tokenizer_path:
  desc: null
  value: llama-7b-hf
max_response_num:
  desc: null
  value: 1
data_dir:
  desc: null
  value: path/to/cleaned_data
data_path:
  desc: null
  value: yahma/alpaca-cleaned
train_data_path:
  desc: null
  value: '[''data/age_bias_contain_score_train.json'']'
eval_data_path:
  desc: null
  value: '[''data/age_bias_contain_score_test.json'']'
data_prefix:
  desc: null
  value: yahma/alpaca-cleaned
eval_at_start:
  desc: null
  value: true
debug_mode:
  desc: null
  value: false
cache_dir:
  desc: null
  value: None
lm_loss_coeff:
  desc: null
  value: 0.5
contrast_loss_coeff:
  desc: null
  value: 0.0
lm_score_thresh:
  desc: null
  value: 0.85
batch_size:
  desc: null
  value: 256
micro_batch_size:
  desc: null
  value: 32
valid_data_size:
  desc: null
  value: 0
lora_r:
  desc: null
  value: 8
lora_alpha:
  desc: null
  value: 16
lora_dropout:
  desc: null
  value: 0.05
lora_target_modules:
  desc: null
  value: '[''q_proj'', ''v_proj'']'
train_batch_size:
  desc: null
  value: 1
eval_batch_size:
  desc: null
  value: 1
